from settings import CAT_MAMMALS, CAT_BIRDS, CAT_REPTILES, CAT_MYTHICAL

# Słownik z definicjami 50 zwierząt
ANIMAL_PRESETS = [
    # --- SSAKI (25) ---
    {
        "id": "fox",
        "name": "Lis",
        "category": CAT_MAMMALS,
        "body_shape": "slender",
        "ear_type": "pointed",
        "snout_type": "fox_snout",
        "tail_type": "bushy",
        "color_body": (220, 90, 40),
        "color_accent": (245, 240, 230),
        "color_eye": (40, 30, 20),
        "special": ["ear_tips_black", "tail_tip_white"],
    },
    {
        "id": "wolf",
        "name": "Wilk",
        "category": CAT_MAMMALS,
        "body_shape": "slender",
        "ear_type": "pointed",
        "snout_type": "dog_snout",
        "tail_type": "bushy",
        "color_body": (130, 135, 145),
        "color_accent": (210, 215, 220),
        "color_eye": (220, 170, 40),
        "special": ["back_fur"],
    },
    {
        "id": "bear",
        "name": "Niedźwiedź",
        "category": CAT_MAMMALS,
        "body_shape": "bear",
        "ear_type": "bear_round",
        "snout_type": "bear_snout",
        "tail_type": "stub",
        "color_body": (95, 60, 35),
        "color_accent": (145, 100, 65),
        "color_eye": (30, 20, 15),
        "special": [],
    },
    {
        "id": "rabbit",
        "name": "Królik",
        "category": CAT_MAMMALS,
        "body_shape": "round",
        "ear_type": "long_rabbit",
        "snout_type": "cat_nose",
        "tail_type": "fluffy_ball",
        "color_body": (235, 220, 205),
        "color_accent": (255, 245, 240),
        "color_eye": (180, 70, 90),
        "special": ["inner_ear_pink"],
    },
    {
        "id": "cat",
        "name": "Kot",
        "category": CAT_MAMMALS,
        "body_shape": "round",
        "ear_type": "pointed",
        "snout_type": "cat_nose",
        "tail_type": "long_thin",
        "color_body": (240, 160, 60),
        "color_accent": (255, 245, 230),
        "color_eye": (60, 190, 120),
        "special": ["whiskers", "stripe_patterns"],
    },
    {
        "id": "dog",
        "name": "Pies",
        "category": CAT_MAMMALS,
        "body_shape": "round",
        "ear_type": "floppy",
        "snout_type": "dog_snout",
        "tail_type": "long_thin",
        "color_body": (195, 135, 75),
        "color_accent": (245, 235, 215),
        "color_eye": (50, 35, 20),
        "special": ["floppy_ears", "eye_patch"],
    },
    {
        "id": "deer",
        "name": "Jeleń",
        "category": CAT_MAMMALS,
        "body_shape": "slender",
        "ear_type": "pointed",
        "snout_type": "dog_snout",
        "tail_type": "stub",
        "color_body": (160, 95, 50),
        "color_accent": (245, 230, 210),
        "color_eye": (45, 30, 20),
        "special": ["antlers", "dappled_spots"],
    },
    {
        "id": "panda",
        "name": "Panda",
        "category": CAT_MAMMALS,
        "body_shape": "bear",
        "ear_type": "bear_round",
        "snout_type": "bear_snout",
        "tail_type": "stub",
        "color_body": (245, 245, 245),
        "color_accent": (35, 35, 40),
        "color_eye": (20, 20, 25),
        "special": ["panda_patches"],
    },
    {
        "id": "raccoon",
        "name": "Szop Pracacz",
        "category": CAT_MAMMALS,
        "body_shape": "round",
        "ear_type": "pointed",
        "snout_type": "fox_snout",
        "tail_type": "bushy",
        "color_body": (120, 125, 130),
        "color_accent": (230, 230, 230),
        "color_eye": (30, 30, 35),
        "special": ["raccoon_mask", "ringed_tail"],
    },
    {
        "id": "squirrel",
        "name": "Wiewiórka",
        "category": CAT_MAMMALS,
        "body_shape": "round",
        "ear_type": "feather_tufts",
        "snout_type": "cat_nose",
        "tail_type": "bushy",
        "color_body": (215, 105, 35),
        "color_accent": (250, 240, 220),
        "color_eye": (40, 25, 15),
        "special": ["tufted_ears"],
    },
    {
        "id": "otter",
        "name": "Wydra",
        "category": CAT_MAMMALS,
        "body_shape": "slender",
        "ear_type": "rounded",
        "snout_type": "cat_nose",
        "tail_type": "long_thin",
        "color_body": (110, 75, 45),
        "color_accent": (220, 195, 160),
        "color_eye": (35, 25, 15),
        "special": ["whiskers"],
    },
    {
        "id": "beaver",
        "name": "Bóbr",
        "category": CAT_MAMMALS,
        "body_shape": "bear",
        "ear_type": "rounded",
        "snout_type": "bear_snout",
        "tail_type": "lizard_tail",
        "color_body": (90, 55, 30),
        "color_accent": (150, 105, 65),
        "color_eye": (30, 20, 10),
        "special": ["beaver_tail", "big_teeth"],
    },
    {
        "id": "tiger",
        "name": "Tygrys",
        "category": CAT_MAMMALS,
        "body_shape": "bear",
        "ear_type": "rounded",
        "snout_type": "cat_nose",
        "tail_type": "long_thin",
        "color_body": (235, 130, 30),
        "color_accent": (255, 245, 230),
        "color_eye": (80, 180, 90),
        "special": ["tiger_stripes", "whiskers"],
    },
    {
        "id": "lion",
        "name": "Lew",
        "category": CAT_MAMMALS,
        "body_shape": "bear",
        "ear_type": "rounded",
        "snout_type": "cat_nose",
        "tail_type": "long_thin",
        "color_body": (220, 165, 75),
        "color_accent": (250, 235, 190),
        "color_eye": (140, 95, 35),
        "special": ["lion_mane"],
    },
    {
        "id": "leopard",
        "name": "Lampart",
        "category": CAT_MAMMALS,
        "body_shape": "slender",
        "ear_type": "rounded",
        "snout_type": "cat_nose",
        "tail_type": "long_thin",
        "color_body": (230, 175, 80),
        "color_accent": (255, 245, 220),
        "color_eye": (90, 190, 160),
        "special": ["spot_patterns", "whiskers"],
    },
    {
        "id": "hedgehog",
        "name": "Jeż",
        "category": CAT_MAMMALS,
        "body_shape": "round",
        "ear_type": "rounded",
        "snout_type": "fox_snout",
        "tail_type": "stub",
        "color_body": (140, 100, 70),
        "color_accent": (235, 210, 180),
        "color_eye": (20, 20, 20),
        "special": ["quills"],
    },
    {
        "id": "koala",
        "name": "Koala",
        "category": CAT_MAMMALS,
        "body_shape": "round",
        "ear_type": "bear_round",
        "snout_type": "bear_snout",
        "tail_type": "stub",
        "color_body": (150, 155, 165),
        "color_accent": (235, 235, 240),
        "color_eye": (40, 30, 25),
        "special": ["fluffy_big_ears", "big_black_nose"],
    },
    {
        "id": "kangaroo",
        "name": "Kangur",
        "category": CAT_MAMMALS,
        "body_shape": "slender",
        "ear_type": "long_rabbit",
        "snout_type": "dog_snout",
        "tail_type": "long_thin",
        "color_body": (185, 120, 65),
        "color_accent": (240, 215, 185),
        "color_eye": (50, 35, 20),
        "special": ["pouch"],
    },
    {
        "id": "pig",
        "name": "Świnia",
        "category": CAT_MAMMALS,
        "body_shape": "round",
        "ear_type": "floppy",
        "snout_type": "pig_snout",
        "tail_type": "curly",
        "color_body": (250, 175, 185),
        "color_accent": (255, 210, 220),
        "color_eye": (40, 30, 40),
        "special": ["piggy_snout"],
    },
    {
        "id": "cow",
        "name": "Krowa",
        "category": CAT_MAMMALS,
        "body_shape": "bear",
        "ear_type": "floppy",
        "snout_type": "pig_snout",
        "tail_type": "long_thin",
        "color_body": (245, 245, 245),
        "color_accent": (40, 40, 45),
        "color_eye": (50, 40, 30),
        "special": ["cow_spots", "horns"],
    },
    {
        "id": "sheep",
        "name": "Owca",
        "category": CAT_MAMMALS,
        "body_shape": "round",
        "ear_type": "floppy",
        "snout_type": "cat_nose",
        "tail_type": "stub",
        "color_body": (240, 235, 220),
        "color_accent": (60, 55, 50),
        "color_eye": (40, 35, 30),
        "special": ["wooly_coat"],
    },
    {
        "id": "horse",
        "name": "Koń",
        "category": CAT_MAMMALS,
        "body_shape": "slender",
        "ear_type": "pointed",
        "snout_type": "dog_snout",
        "tail_type": "bushy",
        "color_body": (140, 75, 35),
        "color_accent": (235, 225, 210),
        "color_eye": (30, 20, 15),
        "special": ["horse_mane"],
    },
    {
        "id": "badger",
        "name": "Borsuk",
        "category": CAT_MAMMALS,
        "body_shape": "round",
        "ear_type": "rounded",
        "snout_type": "fox_snout",
        "tail_type": "stub",
        "color_body": (70, 75, 80),
        "color_accent": (240, 240, 245),
        "color_eye": (25, 25, 30),
        "special": ["badger_stripes"],
    },
    {
        "id": "ferret",
        "name": "Fretka",
        "category": CAT_MAMMALS,
        "body_shape": "slender",
        "ear_type": "rounded",
        "snout_type": "fox_snout",
        "tail_type": "long_thin",
        "color_body": (210, 180, 140),
        "color_accent": (60, 45, 35),
        "color_eye": (30, 20, 15),
        "special": ["ferret_mask"],
    },
    {
        "id": "bat",
        "name": "Nietoperz",
        "category": CAT_MAMMALS,
        "body_shape": "round",
        "ear_type": "pointed",
        "snout_type": "cat_nose",
        "tail_type": "stub",
        "color_body": (65, 55, 75),
        "color_accent": (140, 120, 160),
        "color_eye": (240, 200, 60),
        "special": ["bat_wings"],
    },

    # --- PTAKI (10) ---
    {
        "id": "owl",
        "name": "Sowa",
        "category": CAT_BIRDS,
        "body_shape": "bird",
        "ear_type": "feather_tufts",
        "snout_type": "beak_curved",
        "tail_type": "feather_fan",
        "color_body": (150, 105, 60),
        "color_accent": (245, 235, 210),
        "color_eye": (240, 180, 30),
        "special": ["owl_face", "wings"],
    },
    {
        "id": "eagle",
        "name": "Orzeł",
        "category": CAT_BIRDS,
        "body_shape": "bird",
        "ear_type": "none",
        "snout_type": "beak_curved",
        "tail_type": "feather_fan",
        "color_body": (85, 55, 30),
        "color_accent": (250, 250, 250),
        "color_eye": (230, 190, 40),
        "special": ["eagle_head", "wings"],
    },
    {
        "id": "parrot",
        "name": "Papuga",
        "category": CAT_BIRDS,
        "body_shape": "bird",
        "ear_type": "none",
        "snout_type": "beak_curved",
        "tail_type": "feather_fan",
        "color_body": (235, 45, 45),
        "color_accent": (45, 180, 235),
        "color_eye": (250, 250, 250),
        "special": ["rainbow_feathers", "wings"],
    },
    {
        "id": "penguin",
        "name": "Pingwin",
        "category": CAT_BIRDS,
        "body_shape": "bird",
        "ear_type": "none",
        "snout_type": "beak_small",
        "tail_type": "stub",
        "color_body": (35, 40, 50),
        "color_accent": (250, 250, 250),
        "color_eye": (30, 30, 35),
        "special": ["penguin_tuxedo", "wings"],
    },
    {
        "id": "duck",
        "name": "Kaczka",
        "category": CAT_BIRDS,
        "body_shape": "bird",
        "ear_type": "none",
        "snout_type": "beak_toucan",
        "tail_type": "feather_fan",
        "color_body": (60, 150, 90),
        "color_accent": (140, 95, 50),
        "color_eye": (30, 30, 30),
        "special": ["mallard_head", "wings"],
    },
    {
        "id": "flamingo",
        "name": "Flaming",
        "category": CAT_BIRDS,
        "body_shape": "bird",
        "ear_type": "none",
        "snout_type": "beak_curved",
        "tail_type": "feather_fan",
        "color_body": (250, 130, 160),
        "color_accent": (255, 190, 210),
        "color_eye": (250, 250, 250),
        "special": ["long_neck", "wings"],
    },
    {
        "id": "crow",
        "name": "Kruk",
        "category": CAT_BIRDS,
        "body_shape": "bird",
        "ear_type": "none",
        "snout_type": "beak_small",
        "tail_type": "feather_fan",
        "color_body": (40, 42, 48),
        "color_accent": (80, 85, 100),
        "color_eye": (180, 190, 210),
        "special": ["glossy_wings", "wings"],
    },
    {
        "id": "hummingbird",
        "name": "Koliber",
        "category": CAT_BIRDS,
        "body_shape": "bird",
        "ear_type": "none",
        "snout_type": "beak_small",
        "tail_type": "feather_fan",
        "color_body": (40, 190, 160),
        "color_accent": (220, 70, 140),
        "color_eye": (30, 30, 30),
        "special": ["fast_wings", "wings"],
    },
    {
        "id": "swan",
        "name": "Łabędź",
        "category": CAT_BIRDS,
        "body_shape": "bird",
        "ear_type": "none",
        "snout_type": "beak_small",
        "tail_type": "feather_fan",
        "color_body": (250, 250, 255),
        "color_accent": (235, 140, 40),
        "color_eye": (30, 30, 30),
        "special": ["graceful_neck", "wings"],
    },
    {
        "id": "toucan",
        "name": "Tukan",
        "category": CAT_BIRDS,
        "body_shape": "bird",
        "ear_type": "none",
        "snout_type": "beak_toucan",
        "tail_type": "feather_fan",
        "color_body": (35, 35, 40),
        "color_accent": (245, 200, 50),
        "color_eye": (50, 160, 220),
        "special": ["giant_beak", "wings"],
    },

    # --- GADY I PŁAZY / MORSKIE (8) ---
    {
        "id": "frog",
        "name": "Żaba",
        "category": CAT_REPTILES,
        "body_shape": "round",
        "ear_type": "none",
        "snout_type": "reptile_snout",
        "tail_type": "stub",
        "color_body": (90, 190, 70),
        "color_accent": (210, 240, 130),
        "color_eye": (240, 200, 30),
        "special": ["big_frog_eyes"],
    },
    {
        "id": "turtle",
        "name": "Żółw",
        "category": CAT_REPTILES,
        "body_shape": "lizard",
        "ear_type": "none",
        "snout_type": "reptile_snout",
        "tail_type": "stub",
        "color_body": (110, 160, 85),
        "color_accent": (80, 60, 40),
        "color_eye": (30, 30, 30),
        "special": ["turtle_shell"],
    },
    {
        "id": "chameleon",
        "name": "Kameleon",
        "category": CAT_REPTILES,
        "body_shape": "lizard",
        "ear_type": "none",
        "snout_type": "reptile_snout",
        "tail_type": "curly",
        "color_body": (70, 210, 140),
        "color_accent": (230, 220, 60),
        "color_eye": (240, 120, 40),
        "special": ["360_eyes", "crest"],
    },
    {
        "id": "lizard",
        "name": "Jaszczurka",
        "category": CAT_REPTILES,
        "body_shape": "lizard",
        "ear_type": "none",
        "snout_type": "reptile_snout",
        "tail_type": "lizard_tail",
        "color_body": (140, 180, 60),
        "color_accent": (230, 190, 70),
        "color_eye": (40, 40, 20),
        "special": ["frill_neck"],
    },
    {
        "id": "axolotl",
        "name": "Axolotl",
        "category": CAT_REPTILES,
        "body_shape": "round",
        "ear_type": "feather_tufts",
        "snout_type": "cat_nose",
        "tail_type": "lizard_tail",
        "color_body": (250, 180, 200),
        "color_accent": (235, 90, 140),
        "color_eye": (30, 20, 30),
        "special": ["axolotl_gills"],
    },
    {
        "id": "snake",
        "name": "Wąż",
        "category": CAT_REPTILES,
        "body_shape": "lizard",
        "ear_type": "none",
        "snout_type": "reptile_snout",
        "tail_type": "long_thin",
        "color_body": (75, 170, 95),
        "color_accent": (230, 225, 140),
        "color_eye": (230, 180, 30),
        "special": ["forked_tongue"],
    },
    {
        "id": "dolphin",
        "name": "Delfin",
        "category": CAT_REPTILES,
        "body_shape": "slender",
        "ear_type": "fin",
        "snout_type": "reptile_snout",
        "tail_type": "lizard_tail",
        "color_body": (100, 160, 210),
        "color_accent": (230, 240, 250),
        "color_eye": (30, 40, 60),
        "special": ["fin_top"],
    },
    {
        "id": "shark",
        "name": "Rekin",
        "category": CAT_REPTILES,
        "body_shape": "slender",
        "ear_type": "fin",
        "snout_type": "dragon_snout",
        "tail_type": "lizard_tail",
        "color_body": (120, 135, 150),
        "color_accent": (240, 240, 245),
        "color_eye": (20, 25, 35),
        "special": ["shark_fin", "sharp_teeth"],
    },

    # --- STWORZENIA BAŚNIOWE (7) ---
    {
        "id": "dragon",
        "name": "Smok",
        "category": CAT_MYTHICAL,
        "body_shape": "dragon",
        "ear_type": "horns",
        "snout_type": "dragon_snout",
        "tail_type": "dragon_tail",
        "color_body": (195, 45, 55),
        "color_accent": (245, 190, 60),
        "color_eye": (245, 210, 40),
        "special": ["wings", "horns", "smoke_breath"],
    },
    {
        "id": "phoenix",
        "name": "Feniks",
        "category": CAT_MYTHICAL,
        "body_shape": "bird",
        "ear_type": "feather_tufts",
        "snout_type": "beak_curved",
        "tail_type": "feather_fan",
        "color_body": (240, 90, 35),
        "color_accent": (250, 210, 50),
        "color_eye": (255, 235, 100),
        "special": ["fire_aura", "wings"],
    },
    {
        "id": "unicorn",
        "name": "Jednorożec",
        "category": CAT_MYTHICAL,
        "body_shape": "slender",
        "ear_type": "pointed",
        "snout_type": "dog_snout",
        "tail_type": "bushy",
        "color_body": (250, 245, 255),
        "color_accent": (240, 150, 220),
        "color_eye": (160, 90, 220),
        "special": ["unicorn_horn", "rainbow_mane"],
    },
    {
        "id": "griffin",
        "name": "Gryf",
        "category": CAT_MYTHICAL,
        "body_shape": "bear",
        "ear_type": "feather_tufts",
        "snout_type": "beak_curved",
        "tail_type": "long_thin",
        "color_body": (210, 160, 70),
        "color_accent": (245, 230, 190),
        "color_eye": (220, 150, 30),
        "special": ["wings", "feather_collar"],
    },
    {
        "id": "forest_sprite",
        "name": "Leśny Duszek",
        "category": CAT_MYTHICAL,
        "body_shape": "round",
        "ear_type": "pointed",
        "snout_type": "cat_nose",
        "tail_type": "fluffy_ball",
        "color_body": (70, 175, 120),
        "color_accent": (240, 240, 150),
        "color_eye": (250, 250, 250),
        "special": ["glowing_aura", "leaf_headgear"],
    },
    {
        "id": "kitty_dragon",
        "name": "Kituś-Smok",
        "category": CAT_MYTHICAL,
        "body_shape": "round",
        "ear_type": "horns",
        "snout_type": "cat_nose",
        "tail_type": "dragon_tail",
        "color_body": (170, 110, 220),
        "color_accent": (245, 200, 240),
        "color_eye": (80, 230, 210),
        "special": ["wings", "whiskers", "horns"],
    },
    {
        "id": "glow_deer",
        "name": "Świetlisty Jelonek",
        "category": CAT_MYTHICAL,
        "body_shape": "slender",
        "ear_type": "pointed",
        "snout_type": "dog_snout",
        "tail_type": "stub",
        "color_body": (60, 130, 180),
        "color_accent": (160, 230, 250),
        "color_eye": (220, 250, 255),
        "special": ["crystal_antlers", "star_spots"],
    },
]

# Pomocnicza mapa po id
ANIMAL_BY_ID = {preset["id"]: preset for preset in ANIMAL_PRESETS}
